<a href="https://colab.research.google.com/github/Kancherla-Amulya/2303A51242-PnS/blob/main/pns_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[9,10,11],[15,16,17],[21,22,23],[35,36,37]])
print(A)

[[ 9 10 11]
 [15 16 17]
 [21 22 23]
 [35 36 37]]


In [3]:
print(A[0,:])
print(A[1,:])
print(A[2,:])
print(A[3,:])

[ 9 10 11]
[15 16 17]
[21 22 23]
[35 36 37]


In [4]:
print(A[:,2])

[11 17 23 37]


In [5]:
print(A[2,:])

[21 22 23]


In [6]:
print(np.size(A))

12


In [7]:
print(A[2,2])

23
